index:
    path: /
    controller: App\Controller\DefaultController::index
#admin:
    #path: /admin
    #controller: App\Controller\AdminController::admin
login:
    path: /admin/login
    controller: App\Controller\AdminController::login
logout:
    path: /logout
addSet:
    path: /admin/add
    controller: App\Controller\AdminController::add
deleteSet:
    path: /admin/delete/{id}
    controller: App\Controller\AdminController::delete
updateSet:
    path: /admin/update/{id}
    controller: App\Controller\AdminController::update
about:
    path: /about
    controller: App\Controller\AboutController::about
gigs:
    path: /gigs
    controller: App\Controller\GigsController::gigs
contact:
    path: /contact
    controller: App\Controller\ContactController::contact
facebook:
    resource: App\Controller\FacebookController
    type: annotation