index:
    path: /
    controller: App\Controller\DefaultController::index
admin:
    path: /admin
    controller: App\Controller\AdminController::index
login:
    path: /admin/login
    controller: App\Controller\AdminController::login
logout:
    path: /logout