index:
    path: /
    controller: App\Controller\DefaultController::index
admin:
    path: /admin
    controller: App\Controller\AdminController::admin
login:
    path: /admin/login
    controller: App\Controller\AdminController::login
logout:
    path: /logout
addSet:
    path: /admin/add
    controller: App\Controller\AdminController::add
deleteSet:
    path: /admin/delete/{id}
    controller: App\Controller\AdminController::delete